[theme]
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
